-- =======================================================
-- SQL SCHEMA FOR SUPABASE (POSTGRESQL)
-- Stock & Expiry Tracker with LINE Flex Notifications
-- =======================================================

-- 1. Create PRODUCTS table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT DEFAULT 'วัตถุดิบ',
  unit TEXT NOT NULL DEFAULT 'ชิ้น',
  safety_stock NUMERIC NOT NULL DEFAULT 0,
  expiry_warning_days INTEGER NOT NULL DEFAULT 7,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create INVENTORY BATCHES table
CREATE TABLE IF NOT EXISTS inventory_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  lot_number TEXT,
  quantity NUMERIC NOT NULL DEFAULT 0,
  initial_quantity NUMERIC NOT NULL DEFAULT 0,
  expiry_date DATE NOT NULL,
  received_date DATE NOT NULL DEFAULT CURRENT_DATE,
  cost_per_unit NUMERIC DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create USAGE LOGS table
CREATE TABLE IF NOT EXISTS usage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  batch_id BIGINT REFERENCES inventory_batches(id) ON DELETE SET NULL,
  quantity NUMERIC NOT NULL,
  type TEXT NOT NULL DEFAULT 'USE',
  used_date DATE NOT NULL DEFAULT CURRENT_DATE,
  used_by TEXT,
  purpose TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create SETTINGS table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Default Settings
INSERT INTO settings (key, value) VALUES
  ('line_channel_access_token', ''),
  ('line_target_id', ''),
  ('enable_low_stock_alert', '1'),
  ('enable_expiry_alert', '1'),
  ('daily_alert_time', '08:00'),
  ('default_expiry_alert_days', '7'),
  ('last_alert_sent_at', '')
ON CONFLICT (key) DO NOTHING;

-- Initial Demo Data (Matching reference screenshot)
DO $$
DECLARE
  bread_id BIGINT;
  chicken_id BIGINT;
  ham_id BIGINT;
  cheese_id BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM products LIMIT 1) THEN
    -- 1. Bread (Total 110 Fl, Safety 200 Fl)
    INSERT INTO products (name, category, unit, safety_stock, expiry_warning_days)
    VALUES ('Bread', 'เบเกอรี่', 'Fl', 200, 5) RETURNING id INTO bread_id;
    
    INSERT INTO inventory_batches (product_id, lot_number, quantity, initial_quantity, expiry_date, received_date, notes)
    VALUES 
      (bread_id, 'LOT-BR01', 50, 100, CURRENT_DATE + INTERVAL '3 days', CURRENT_DATE - INTERVAL '2 days', 'ล็อตแรก'),
      (bread_id, 'LOT-BR02', 60, 100, CURRENT_DATE + INTERVAL '6 days', CURRENT_DATE - INTERVAL '1 day', 'ล็อตสอง');

    -- 2. Chicken Slice (Total 1000 Piece, Safety 2000 Piece)
    INSERT INTO products (name, category, unit, safety_stock, expiry_warning_days)
    VALUES ('Chicken Slice', 'เนื้อสัตว์', 'Piece', 2000, 7) RETURNING id INTO chicken_id;
    
    INSERT INTO inventory_batches (product_id, lot_number, quantity, initial_quantity, expiry_date, received_date, notes)
    VALUES (chicken_id, 'LOT-CK01', 1000, 2000, CURRENT_DATE + INTERVAL '14 days', CURRENT_DATE - INTERVAL '3 days', 'อกไก่สไลด์แช่เย็น');

    -- 3. Ham (Total 1 Kg, Safety 1 Kg)
    INSERT INTO products (name, category, unit, safety_stock, expiry_warning_days)
    VALUES ('Ham', 'เนื้อสัตว์', 'Kg', 1, 7) RETURNING id INTO ham_id;
    
    INSERT INTO inventory_batches (product_id, lot_number, quantity, initial_quantity, expiry_date, received_date, notes)
    VALUES (ham_id, 'LOT-HM01', 1, 5, CURRENT_DATE + INTERVAL '4 days', CURRENT_DATE - INTERVAL '5 days', 'แฮมหมูรมควัน');

    -- 4. Cheddar Cheese (Expiring in 2 days)
    INSERT INTO products (name, category, unit, safety_stock, expiry_warning_days)
    VALUES ('Cheddar Cheese', 'ผลิตภัณฑ์นม', 'Pack', 5, 10) RETURNING id INTO cheese_id;
    
    INSERT INTO inventory_batches (product_id, lot_number, quantity, initial_quantity, expiry_date, received_date, notes)
    VALUES (cheese_id, 'LOT-CH01', 12, 15, CURRENT_DATE + INTERVAL '2 days', CURRENT_DATE - INTERVAL '10 days', 'ชีสแผ่น');
  END IF;
END $$;

