-- =======================================================
-- SQL SCHEMA FOR SUPABASE (POSTGRESQL)
-- Stock & Expiry Tracker with LINE Flex Notifications
-- =======================================================

-- 1. Create PRODUCTS table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT DEFAULT 'วัตถุดิบ',
  unit TEXT NOT NULL DEFAULT 'ชิ้น',
  safety_stock NUMERIC NOT NULL DEFAULT 0,
  expiry_warning_days INTEGER NOT NULL DEFAULT 7,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create INVENTORY BATCHES table
CREATE TABLE IF NOT EXISTS inventory_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  lot_number TEXT,
  quantity NUMERIC NOT NULL DEFAULT 0,
  initial_quantity NUMERIC NOT NULL DEFAULT 0,
  expiry_date DATE NOT NULL,
  received_date DATE NOT NULL DEFAULT CURRENT_DATE,
  cost_per_unit NUMERIC DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create USAGE LOGS table
CREATE TABLE IF NOT EXISTS usage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  batch_id BIGINT REFERENCES inventory_batches(id) ON DELETE SET NULL,
  quantity NUMERIC NOT NULL,
  type TEXT NOT NULL DEFAULT 'USE',
  used_date DATE NOT NULL DEFAULT CURRENT_DATE,
  used_by TEXT,
  purpose TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create SETTINGS table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- 5. Create LINE RECIPIENTS table (Multiple Users & Groups)
CREATE TABLE IF NOT EXISTS line_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  target_id TEXT NOT NULL UNIQUE,
  type TEXT DEFAULT 'USER', -- 'USER' or 'GROUP'
  is_active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Default Settings
INSERT INTO settings (key, value) VALUES
  ('line_channel_access_token', ''),
  ('line_target_id', ''),
  ('enable_low_stock_alert', '1'),
  ('enable_expiry_alert', '1'),
  ('daily_alert_time', '08:00'),
  ('default_expiry_alert_days', '7'),
  ('last_alert_sent_at', '')
ON CONFLICT (key) DO NOTHING;

-- Initial Data: 54 Dairy Queen Inventory Items (Dry goods)
INSERT INTO products (name, category, unit, safety_stock, expiry_warning_days)
VALUES
  ('ผงโกโก้', 'ของแห้ง', 'EA', 1, 7),
  ('ช้อนสั้น', 'ของแห้ง', 'PACK', 1, 7),
  ('ช้อนยาว', 'ของแห้ง', 'PACK', 1, 7),
  ('นมจืด', 'ของแห้ง', 'PACK', 1, 7),
  ('แก้วซันเดย์', 'ของแห้ง', 'PACK', 1, 7),
  ('หลอด', 'ของแห้ง', 'PACK', 1, 7),
  ('โคน', 'ของแห้ง', 'PACK', 1, 7),
  ('Oreo', 'ของแห้ง', 'PACK', 1, 7),
  ('แก้ว8oz', 'ของแห้ง', 'PACK', 1, 7),
  ('แก้ว12oz', 'ของแห้ง', 'PACK', 1, 7),
  ('แก้ว16oz BZ', 'ของแห้ง', 'PACK', 1, 7),
  ('แนปกิ้น', 'ของแห้ง', 'PACK', 1, 7),
  ('Box hotdag', 'ของแห้ง', 'PACK', 1, 7),
  ('Wrap hotdog', 'ของแห้ง', 'PACK', 1, 7),
  ('กาแฟ', 'ของแห้ง', 'PACK', 1, 7),
  ('ซอสมะเขือเทศ', 'ของแห้ง', 'BAG', 1, 7),
  ('ซอสพริก', 'ของแห้ง', 'BAG', 1, 7),
  ('โกโก้ฟัด', 'ของแห้ง', 'BAG', 1, 7),
  ('ช็อคดิป', 'ของแห้ง', 'BAG', 1, 7),
  ('คาราเมล', 'ของแห้ง', 'BAG', 1, 7),
  ('ช็อคท็อปปิ้ง', 'ของแห้ง', 'BAG', 1, 7),
  ('อัลมอนด์', 'ของแห้ง', 'BAG', 1, 7),
  ('ชาเขียว', 'ของแห้ง', 'BAG', 1, 7),
  ('ถุงขาว', 'ของแห้ง', 'PACK', 1, 7),
  ('แก๊สบอม', 'ของแห้ง', 'BOX', 1, 7),
  ('Kitkat', 'ของแห้ง', 'BOX', 1, 7),
  ('ปอกโคน', 'ของแห้ง', 'PACK', 1, 7),
  ('Purra', 'ของแห้ง', 'PACK', 1, 7),
  ('มีด', 'ของแห้ง', 'PACK', 1, 7),
  ('ส้อม', 'ของแห้ง', 'PACK', 1, 7),
  ('วอวิค', 'ของแห้ง', 'CS', 1, 7),
  ('โรล เปปเซฟ', 'ของแห้ง', 'EA', 1, 7),
  ('เอเวียงฝาแดง', 'ของแห้ง', 'CS', 1, 7),
  ('ชเวปเขียว', 'ของแห้ง', 'PACK', 1, 7),
  ('ชเวปม่วง', 'ของแห้ง', 'CS', 1, 7),
  ('ชเวปชมพู', 'ของแห้ง', 'PACK', 1, 7),
  ('แก้ว16oz', 'ของแห้ง', 'PACK', 1, 7),
  ('ฝา BZ.16 oz', 'ของแห้ง', 'PACK', 1, 7),
  ('แก้วCoke 32oz', 'ของแห้ง', 'PACK', 1, 7),
  ('ฝาแก้ว 32 oz', 'ของแห้ง', 'PACK', 1, 7),
  ('แก้ว 22 oz', 'ของแห้ง', 'PACK', 1, 7),
  ('ฝาแก้ว 22 oz', 'ของแห้ง', 'PACK', 1, 7),
  ('ถุงขยะใหญ่', 'ของแห้ง', 'PACK', 1, 7),
  ('Hand towel', 'ของแห้ง', 'PACK', 1, 7),
  ('Perrier', 'ของแห้ง', 'PACK', 1, 7),
  ('Perrier Lemon', 'ของแห้ง', 'PACK', 1, 7),
  ('Cokeกด', 'ของแห้ง', 'CS', 1, 7),
  ('Cokeขวดฝาแดง', 'ของแห้ง', 'CS', 1, 7),
  ('ถุงมือS', 'ของแห้ง', 'BOX', 1, 7),
  ('ถุงมือM', 'ของแห้ง', 'BOX', 1, 7),
  ('ถังแดง', 'ของแห้ง', 'EA', 1, 7),
  ('ขวดใส่ท็อปปิ้ง', 'ของแห้ง', 'EA', 1, 7),
  ('มัลติ', 'ของแห้ง', 'EA', 1, 7),
  ('ถุงขยะเล็ก', 'ของแห้ง', 'PACK', 1, 7)
ON CONFLICT (name) DO NOTHING;

-- Initial Batch for 'ฝา BZ.16 oz' (5 packs)
DO $$
DECLARE
  bz_id BIGINT;
BEGIN
  SELECT id INTO bz_id FROM products WHERE name = 'ฝา BZ.16 oz' LIMIT 1;
  IF bz_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM inventory_batches WHERE product_id = bz_id) THEN
    INSERT INTO inventory_batches (product_id, lot_number, quantity, initial_quantity, expiry_date, received_date, notes)
    VALUES (bz_id, 'LOT-INIT', 5, 5, CURRENT_DATE + INTERVAL '6 months', CURRENT_DATE, 'ยอดยกมา 5 แพ็ค');
  END IF;
END $$;

